<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/25 13:44:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=prac1',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
