<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/09/25 22:07:04
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sftesterdoctrine' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinedatabase' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinegenerator' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinecreatemodeltables' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedqltask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildschematask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrineinsertsqltask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildsqltask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildfilterstask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinedataloadtask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildformstask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinedropdbtask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildmodeltask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildtask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuilddbtask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedatadumptask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinemigratetask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebasetask' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrineroutecollection' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrinerecordi18nfilter' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinecli' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfvalidatordoctrinechoice' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfwebdebugpaneldoctrine' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinepager' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineexception' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'swift_doctrinespool' => '/usr/share/pear/symfony/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',

  // project
  'basepageformfilter' => '/home/k-masuda/dev/php/sf14sample/lib/filter/doctrine/base/BasePageFormFilter.class.php',
  'pageformfilter' => '/home/k-masuda/dev/php/sf14sample/lib/filter/doctrine/PageFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/k-masuda/dev/php/sf14sample/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'basepageform' => '/home/k-masuda/dev/php/sf14sample/lib/form/doctrine/base/BasePageForm.class.php',
  'baseformdoctrine' => '/home/k-masuda/dev/php/sf14sample/lib/form/doctrine/BaseFormDoctrine.class.php',
  'pageform' => '/home/k-masuda/dev/php/sf14sample/lib/form/doctrine/PageForm.class.php',
  'baseform' => '/home/k-masuda/dev/php/sf14sample/lib/form/BaseForm.class.php',

  // project_model
  'pagetable' => '/home/k-masuda/dev/php/sf14sample/lib/model/doctrine/PageTable.class.php',
  'basepage' => '/home/k-masuda/dev/php/sf14sample/lib/model/doctrine/base/BasePage.class.php',
  'page' => '/home/k-masuda/dev/php/sf14sample/lib/model/doctrine/Page.class.php',

  // application
  'myuser' => '/home/k-masuda/dev/php/sf14sample/apps/frontend/lib/myUser.class.php',

  // modules
);
