<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/25 22:07:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfonyband',
  'username' => 'root',
  'password' => 'pr0c0nvkm8',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_unicode_ci',
  ),
  'name' => 'doctrine',
)),);
